services:
  nginx:
    image: nginx:alpine
    container_name: gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - api_backend
      - estadistica_mapa
    networks:
      - esdop_net

  frontend:
    build: ./front
    container_name: front
    restart: always
    expose:
      - "80"
    networks:
      - esdop_net

  api_backend:
    image: esdop-api-backend:latest
    build:
      context: ./bakeng/ESDOP-BACKEND-NUEVO
      dockerfile: Dockerfile
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: always
    env_file:
      - ./bakeng/ESDOP-BACKEND-NUEVO/.env
    expose:
      - "8000"
    networks:
      - esdop_net

  estadistica_mapa:
    image: esdop-estadistica-mapa:latest
    build:
      context: ./bakeng/ESDOP-BACKEND-NUEVO
      dockerfile: Dockerfile
    command: ["uvicorn", "estadistica_mapa.estadistica_pesada:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: always
    env_file:
      - ./bakeng/ESDOP-BACKEND-NUEVO/.env
    expose:
      - "8000"
    networks:
      - esdop_net

networks:
  esdop_net:
    driver: bridge
